- name: "Download vault repo"
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: "install hashicorp vault repo"
  ansible.builtin.dnf:
    name: vault
    state: installed


- name: "copy vault hcl file"
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: "restart hashicorp vault repo"
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: true

